openapi: 3.0.0
paths:
  /:
    get:
      operationId: AppController_getHello
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - App
  /api/auth/login:
    post:
      operationId: AuthController_login
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Auth
  /api/auth/callback:
    get:
      operationId: AuthController_callback
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Auth
  /api/auth/me:
    get:
      operationId: AuthController_getUserInfo
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Auth
  /api/auth/refresh:
    post:
      operationId: AuthController_refreshToken
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Auth
  /api/auth/logout:
    post:
      operationId: AuthController_logout
      parameters: []
      responses:
        '200':
          description: ''
      tags:
        - Auth
  /api/gdrive/list:
    get:
      operationId: GDriveController_listFolder
      parameters:
        - name: folderId
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - GDrive
  /api/gdrive/search:
    get:
      operationId: GDriveController_search
      parameters:
        - name: folderId
          required: true
          in: query
          schema:
            type: string
        - name: query
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - GDrive
  /api/player/stream/{fileId}:
    get:
      operationId: PlayerController_streamVideo
      parameters:
        - name: fileId
          required: true
          in: path
          schema:
            type: string
        - name: range
          required: true
          in: header
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Player
  /api/player/comments/{videoFileId}:
    get:
      operationId: PlayerController_getComments
      parameters:
        - name: videoFileId
          required: true
          in: path
          schema:
            type: string
        - name: folderId
          required: true
          in: query
          schema:
            type: string
      responses:
        '200':
          description: ''
      tags:
        - Player
  /api/nicovideo/download/comments:
    post:
      operationId: NicovideoController_downloadComments
      parameters: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DownloadCommentRequestDto'
      responses:
        '201':
          description: ''
      tags:
        - Nicovideo
info:
  title: danmaku API
  description: Danmaku API documentation
  version: '1.0'
  contact: {}
tags: []
servers: []
components:
  schemas:
    DownloadCommentRequestDto:
      type: object
      properties: {}
