/**
 * This file is AUTO GENERATED by [msw-auto-mock](https://github.com/zoubingwu/msw-auto-mock)
 * Feel free to commit/edit it as you need.
 */
/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import { HttpResponse, http } from "msw";
import { faker } from "@faker-js/faker";

faker.seed(1);

const baseURL = "";
const MAX_ARRAY_LENGTH = 20;
const MAX_STRING_LENGTH = 42;

// Map to store counters for each API endpoint
const apiCounters = new Map();

const next = (apiKey) => {
  let currentCount = apiCounters.get(apiKey) ?? 0;
  if (currentCount === Number.MAX_SAFE_INTEGER - 1) {
    currentCount = 0;
  }
  apiCounters.set(apiKey, currentCount + 1);
  return currentCount;
};

export const handlers = [
  http.post(`${baseURL}/api/kakolog/download/comments`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("post")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [
        await getKakologControllerDownloadComments200Response(),
        { status: 200 },
      ],
    ];

    const [body, init] =
      resultArray[
        next(`post /api/kakolog/download/comments`) % resultArray.length
      ];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.post(
    `${baseURL}/api/nicovideo/download/comments`,
    async ({ request }) => {
      const shouldEchoRequestBody = false;
      let requestJson = null;
      if (shouldEchoRequestBody && ["post", "put", "patch"].includes("post")) {
        try {
          requestJson = await request.clone().json();
        } catch (e) {
          requestJson = null;
        }
      }

      const resultArray = [
        [
          await getNicovideoControllerDownloadComments201Response(),
          { status: 201 },
        ],
      ];

      const [body, init] =
        resultArray[
          next(`post /api/nicovideo/download/comments`) % resultArray.length
        ];
      const responseJson =
        requestJson && body && typeof body === "object" && !Array.isArray(body)
          ? { ...body, ...requestJson }
          : body;
      return HttpResponse.json(responseJson, init);
    },
  ),
  http.get(`${baseURL}/api/auth/me`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [await getAuthControllerGetUserInfo200Response(), { status: 200 }],
    ];

    const [body, init] =
      resultArray[next(`get /api/auth/me`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.patch(`${baseURL}/api/user-settings/reset`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("patch")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [
        await getUserSettingsControllerResetSettings200Response(),
        { status: 200 },
      ],
    ];

    const [body, init] =
      resultArray[next(`patch /api/user-settings/reset`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.post(`${baseURL}/api/auth/dummy-login`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("post")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [[undefined, { status: 200 }]];

    const [body, init] =
      resultArray[next(`post /api/auth/dummy-login`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.post(`${baseURL}/api/auth/logout`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("post")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [[undefined, { status: 200 }]];

    const [body, init] =
      resultArray[next(`post /api/auth/logout`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.post(`${baseURL}/api/player/token`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("post")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [
        await getPlayerControllerGenerateVideoToken200Response(),
        { status: 200 },
      ],
    ];

    const [body, init] =
      resultArray[next(`post /api/player/token`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.get(`${baseURL}/api/drive-connections`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [await getDriveConnectionControllerList200Response(), { status: 200 }],
    ];

    const [body, init] =
      resultArray[next(`get /api/drive-connections`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.get(`${baseURL}/api/health`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [await getHealthControllerHealth200Response(), { status: 200 }],
    ];

    const [body, init] =
      resultArray[next(`get /api/health`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.get(`${baseURL}/api/user-settings`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [
        await getUserSettingsControllerGetSettings200Response(),
        { status: 200 },
      ],
    ];

    const [body, init] =
      resultArray[next(`get /api/user-settings`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.patch(`${baseURL}/api/user-settings`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("patch")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [
        await getUserSettingsControllerUpdateSettings200Response(),
        { status: 200 },
      ],
    ];

    const [body, init] =
      resultArray[next(`patch /api/user-settings`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.get(`${baseURL}/`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [await getAppControllerGetHello200Response(), { status: 200 }],
    ];

    const [body, init] = resultArray[next(`get /`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.get(
    `${baseURL}/api/drive/connections/:connectionId/files`,
    async ({ request }) => {
      const shouldEchoRequestBody = false;
      let requestJson = null;
      if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
        try {
          requestJson = await request.clone().json();
        } catch (e) {
          requestJson = null;
        }
      }

      const resultArray = [
        [
          await getFolderControllerListFolderByConnection200Response(),
          { status: 200 },
        ],
      ];

      const [body, init] =
        resultArray[
          next(`get /api/drive/connections/:connectionId/files`) %
            resultArray.length
        ];
      const responseJson =
        requestJson && body && typeof body === "object" && !Array.isArray(body)
          ? { ...body, ...requestJson }
          : body;
      return HttpResponse.json(responseJson, init);
    },
  ),
  http.get(
    `${baseURL}/api/drive/connections/:connectionId/search`,
    async ({ request }) => {
      const shouldEchoRequestBody = false;
      let requestJson = null;
      if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
        try {
          requestJson = await request.clone().json();
        } catch (e) {
          requestJson = null;
        }
      }

      const resultArray = [
        [
          await getFolderControllerSearchByConnection200Response(),
          { status: 200 },
        ],
      ];

      const [body, init] =
        resultArray[
          next(`get /api/drive/connections/:connectionId/search`) %
            resultArray.length
        ];
      const responseJson =
        requestJson && body && typeof body === "object" && !Array.isArray(body)
          ? { ...body, ...requestJson }
          : body;
      return HttpResponse.json(responseJson, init);
    },
  ),
  http.get(`${baseURL}/api/auth/callback/:provider`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [[undefined, { status: 200 }]];

    const [body, init] =
      resultArray[
        next(`get /api/auth/callback/:provider`) % resultArray.length
      ];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.get(
    `${baseURL}/api/drive-connections/:provider/callback`,
    async ({ request }) => {
      const shouldEchoRequestBody = false;
      let requestJson = null;
      if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
        try {
          requestJson = await request.clone().json();
        } catch (e) {
          requestJson = null;
        }
      }

      const resultArray = [[undefined, { status: 200 }]];

      const [body, init] =
        resultArray[
          next(`get /api/drive-connections/:provider/callback`) %
            resultArray.length
        ];
      const responseJson =
        requestJson && body && typeof body === "object" && !Array.isArray(body)
          ? { ...body, ...requestJson }
          : body;
      return HttpResponse.json(responseJson, init);
    },
  ),
  http.get(
    `${baseURL}/api/player/comments/:videoFileId`,
    async ({ request }) => {
      const shouldEchoRequestBody = false;
      let requestJson = null;
      if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
        try {
          requestJson = await request.clone().json();
        } catch (e) {
          requestJson = null;
        }
      }

      const resultArray = [
        [await getPlayerControllerGetComments200Response(), { status: 200 }],
      ];

      const [body, init] =
        resultArray[
          next(`get /api/player/comments/:videoFileId`) % resultArray.length
        ];
      const responseJson =
        requestJson && body && typeof body === "object" && !Array.isArray(body)
          ? { ...body, ...requestJson }
          : body;
      return HttpResponse.json(responseJson, init);
    },
  ),
  http.post(`${baseURL}/api/auth/login/:provider`, async ({ request }) => {
    const shouldEchoRequestBody = false;
    let requestJson = null;
    if (shouldEchoRequestBody && ["post", "put", "patch"].includes("post")) {
      try {
        requestJson = await request.clone().json();
      } catch (e) {
        requestJson = null;
      }
    }

    const resultArray = [
      [await getAuthControllerLoginWithProvider200Response(), { status: 200 }],
    ];

    const [body, init] =
      resultArray[next(`post /api/auth/login/:provider`) % resultArray.length];
    const responseJson =
      requestJson && body && typeof body === "object" && !Array.isArray(body)
        ? { ...body, ...requestJson }
        : body;
    return HttpResponse.json(responseJson, init);
  }),
  http.delete(
    `${baseURL}/api/drive-connections/:connectionId`,
    async ({ request }) => {
      const shouldEchoRequestBody = false;
      let requestJson = null;
      if (
        shouldEchoRequestBody &&
        ["post", "put", "patch"].includes("delete")
      ) {
        try {
          requestJson = await request.clone().json();
        } catch (e) {
          requestJson = null;
        }
      }

      const resultArray = [
        [
          await getDriveConnectionControllerDelete200Response(),
          { status: 200 },
        ],
      ];

      const [body, init] =
        resultArray[
          next(`delete /api/drive-connections/:connectionId`) %
            resultArray.length
        ];
      const responseJson =
        requestJson && body && typeof body === "object" && !Array.isArray(body)
          ? { ...body, ...requestJson }
          : body;
      return HttpResponse.json(responseJson, init);
    },
  ),
  http.post(
    `${baseURL}/api/drive-connections/:provider`,
    async ({ request }) => {
      const shouldEchoRequestBody = false;
      let requestJson = null;
      if (shouldEchoRequestBody && ["post", "put", "patch"].includes("post")) {
        try {
          requestJson = await request.clone().json();
        } catch (e) {
          requestJson = null;
        }
      }

      const resultArray = [
        [
          await getDriveConnectionControllerInitiateConnection200Response(),
          { status: 200 },
        ],
      ];

      const [body, init] =
        resultArray[
          next(`post /api/drive-connections/:provider`) % resultArray.length
        ];
      const responseJson =
        requestJson && body && typeof body === "object" && !Array.isArray(body)
          ? { ...body, ...requestJson }
          : body;
      return HttpResponse.json(responseJson, init);
    },
  ),
  http.get(
    `${baseURL}/api/player/stream/:connectionId/:fileId`,
    async ({ request }) => {
      const shouldEchoRequestBody = false;
      let requestJson = null;
      if (shouldEchoRequestBody && ["post", "put", "patch"].includes("get")) {
        try {
          requestJson = await request.clone().json();
        } catch (e) {
          requestJson = null;
        }
      }

      const resultArray = [[undefined, { status: 200 }]];

      const [body, init] =
        resultArray[
          next(`get /api/player/stream/:connectionId/:fileId`) %
            resultArray.length
        ];
      const responseJson =
        requestJson && body && typeof body === "object" && !Array.isArray(body)
          ? { ...body, ...requestJson }
          : body;
      return HttpResponse.json(responseJson, init);
    },
  ),
];

export function getAppControllerGetHello200Response() {
  return faker.lorem.words();
}

export function getAuthControllerLoginWithProvider200Response() {
  return {
    authorize_url: faker.internet.url(),
    state: faker.location.state(),
    expires_in: faker.number.int(),
  };
}

export function getAuthControllerGetUserInfo200Response() {
  return {
    id: faker.string.uuid(),
    email: faker.internet.email(),
    name: faker.person.fullName(),
    picture_url: faker.image.url(),
    last_login: faker.date.anytime().toISOString(),
    drives: (() => {
      const arrayMin = 1;
      const arrayMax = MAX_ARRAY_LENGTH;
      const safeMin = Math.min(arrayMin, arrayMax);
      return [
        ...new Array(faker.number.int({ min: safeMin, max: arrayMax })).keys(),
      ].map((_) => ({
        id: faker.string.uuid(),
        provider: faker.lorem.words(),
        account: faker.lorem.words(),
        status: faker.helpers.arrayElement([
          "error",
          "connected",
          "expired",
          "revoked",
        ]),
        connected_at: faker.date.anytime().toISOString(),
      }));
    })(),
  };
}

export function getDriveConnectionControllerList200Response() {
  return (() => {
    const arrayMin = 1;
    const arrayMax = MAX_ARRAY_LENGTH;
    const safeMin = Math.min(arrayMin, arrayMax);
    return [
      ...new Array(faker.number.int({ min: safeMin, max: arrayMax })).keys(),
    ].map((_) => ({
      id: faker.string.uuid(),
      provider: faker.lorem.words(),
      account: faker.lorem.words(),
      status: faker.helpers.arrayElement([
        "error",
        "connected",
        "expired",
        "revoked",
      ]),
      connected_at: faker.date.anytime().toISOString(),
    }));
  })();
}

export function getDriveConnectionControllerInitiateConnection200Response() {
  return {
    authorize_url: faker.internet.url(),
    state: faker.location.state(),
    expires_in: faker.number.int(),
  };
}

export function getDriveConnectionControllerDelete200Response() {
  return {
    message: faker.lorem.words(),
  };
}

export function getFolderControllerListFolderByConnection200Response() {
  return {
    items: (() => {
      const arrayMin = 1;
      const arrayMax = MAX_ARRAY_LENGTH;
      const safeMin = Math.min(arrayMin, arrayMax);
      return [
        ...new Array(faker.number.int({ min: safeMin, max: arrayMax })).keys(),
      ].map((_) => ({
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        mimeType: faker.lorem.words(),
        size: faker.number.int(),
        modifiedTime: faker.lorem.words(),
        webViewLink: faker.lorem.words(),
        thumbnailLink: faker.lorem.words(),
        parentId: faker.string.uuid(),
      }));
    })(),
    nextPageToken: faker.lorem.words(),
  };
}

export function getFolderControllerSearchByConnection200Response() {
  return {
    items: (() => {
      const arrayMin = 1;
      const arrayMax = MAX_ARRAY_LENGTH;
      const safeMin = Math.min(arrayMin, arrayMax);
      return [
        ...new Array(faker.number.int({ min: safeMin, max: arrayMax })).keys(),
      ].map((_) => ({
        id: faker.string.uuid(),
        name: faker.person.fullName(),
        mimeType: faker.lorem.words(),
        size: faker.number.int(),
        modifiedTime: faker.lorem.words(),
        webViewLink: faker.lorem.words(),
        thumbnailLink: faker.lorem.words(),
        parentId: faker.string.uuid(),
      }));
    })(),
    nextPageToken: faker.lorem.words(),
  };
}

export function getPlayerControllerGetComments200Response() {
  return {
    comments: (() => {
      const arrayMin = 1;
      const arrayMax = MAX_ARRAY_LENGTH;
      const safeMin = Math.min(arrayMin, arrayMax);
      return [
        ...new Array(faker.number.int({ min: safeMin, max: arrayMax })).keys(),
      ].map((_) => ({
        time: faker.number.int(),
        type: faker.lorem.words(),
        size: faker.lorem.words(),
        color: faker.lorem.words(),
        author: faker.lorem.words(),
        text: faker.lorem.words(),
      }));
    })(),
  };
}

export function getPlayerControllerGenerateVideoToken200Response() {
  return {
    token: faker.lorem.words(),
  };
}

export function getNicovideoControllerDownloadComments201Response() {
  return {
    videoId: faker.string.uuid(),
    status: faker.helpers.arrayElement(["completed", "failed"]),
    message: faker.lorem.words(),
    data: {
      title: faker.lorem.words(),
      commentCount: faker.number.int(),
      retrievedCount: faker.number.int(),
      threads: faker.number.int(),
    },
    comments: {
      globalComments: {
        commentCount: faker.number.int(),
        retrievedCount: faker.number.int(),
      },
      threads: (() => {
        const arrayMin = 1;
        const arrayMax = MAX_ARRAY_LENGTH;
        const safeMin = Math.min(arrayMin, arrayMax);
        return [
          ...new Array(
            faker.number.int({ min: safeMin, max: arrayMax }),
          ).keys(),
        ].map((_) => ({
          id: {},
          comments: (() => {
            const arrayMin = 1;
            const arrayMax = MAX_ARRAY_LENGTH;
            const safeMin = Math.min(arrayMin, arrayMax);
            return [
              ...new Array(
                faker.number.int({ min: safeMin, max: arrayMax }),
              ).keys(),
            ].map((_) => ({
              time: faker.number.int(),
              type: faker.lorem.words(),
              size: faker.lorem.words(),
              color: faker.lorem.words(),
              author: faker.lorem.words(),
              text: faker.lorem.words(),
            }));
          })(),
        }));
      })(),
    },
  };
}

export function getKakologControllerDownloadComments200Response() {
  return {
    status: faker.helpers.arrayElement(["completed", "failed"]),
    message: faker.lorem.words(),
    channelId: faker.string.uuid(),
    startTime: faker.number.int(),
    endTime: faker.number.int(),
    commentCount: faker.number.int(),
    retrievedCount: faker.number.int(),
    comments: (() => {
      const arrayMin = 1;
      const arrayMax = MAX_ARRAY_LENGTH;
      const safeMin = Math.min(arrayMin, arrayMax);
      return [
        ...new Array(faker.number.int({ min: safeMin, max: arrayMax })).keys(),
      ].map((_) => ({
        time: faker.number.int(),
        type: faker.helpers.arrayElement(["normal", "top", "bottom"]),
        size: faker.helpers.arrayElement(["small", "medium", "big"]),
        color: faker.lorem.words(),
        author: faker.lorem.words(),
        text: faker.lorem.words(),
      }));
    })(),
  };
}

export function getUserSettingsControllerGetSettings200Response() {
  return {
    id: faker.string.uuid(),
    user_id: faker.string.uuid(),
    theme: faker.lorem.words(),
    language: faker.lorem.words(),
    danmaku_max_count: faker.number.int(),
    ng_words_reg: (() => {
      const arrayMin = 1;
      const arrayMax = MAX_ARRAY_LENGTH;
      const safeMin = Math.min(arrayMin, arrayMax);
      return [
        ...new Array(faker.number.int({ min: safeMin, max: arrayMax })).keys(),
      ].map((_) => faker.lorem.words());
    })(),
    created_at: faker.date.anytime().toISOString(),
    updated_at: faker.date.anytime().toISOString(),
  };
}

export function getUserSettingsControllerUpdateSettings200Response() {
  return {
    id: faker.string.uuid(),
    user_id: faker.string.uuid(),
    theme: faker.lorem.words(),
    language: faker.lorem.words(),
    danmaku_max_count: faker.number.int(),
    ng_words_reg: (() => {
      const arrayMin = 1;
      const arrayMax = MAX_ARRAY_LENGTH;
      const safeMin = Math.min(arrayMin, arrayMax);
      return [
        ...new Array(faker.number.int({ min: safeMin, max: arrayMax })).keys(),
      ].map((_) => faker.lorem.words());
    })(),
    created_at: faker.date.anytime().toISOString(),
    updated_at: faker.date.anytime().toISOString(),
  };
}

export function getUserSettingsControllerResetSettings200Response() {
  return {
    id: faker.string.uuid(),
    user_id: faker.string.uuid(),
    theme: faker.lorem.words(),
    language: faker.lorem.words(),
    danmaku_max_count: faker.number.int(),
    ng_words_reg: (() => {
      const arrayMin = 1;
      const arrayMax = MAX_ARRAY_LENGTH;
      const safeMin = Math.min(arrayMin, arrayMax);
      return [
        ...new Array(faker.number.int({ min: safeMin, max: arrayMax })).keys(),
      ].map((_) => faker.lorem.words());
    })(),
    created_at: faker.date.anytime().toISOString(),
    updated_at: faker.date.anytime().toISOString(),
  };
}

export function getHealthControllerHealth200Response() {
  return {};
}
